# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

docker_version: 27.1.1
docker_archive_checksums:
  amd64:
    27.1.1: 118da6b8fc8e8b6c086ab0dd5e64ee549376c3a3f963723bbc9a46db475bf21f
  arm64:
    27.1.1: 86a395f67a5a23d8eb207ab5a9ab32a51f7fccd8b18dae40887e738db95c6bc4

docker_download_url: "https://download.docker.com/linux/static/stable/{{ ansible_facts['architecture'] | lower }}/docker-{{ docker_version }}.tgz" # noqa: yaml[line-length]

docker_download_dest: "{{ download_artifact_work_directory }}/docker-{{ docker_version }}.tgz"
docker_archive_checksum: "{{ docker_archive_checksums[download_artifact_goarch][docker_version] }}"

# NOTE(mnaser): This is to accomodate for the uninstallation of the old packages
#               that shipped with the operating system
docker_package_name: docker-ce
docker_cfg_dir: /etc/docker
docker_cfg_file: "{{ docker_cfg_dir }}/daemon.json"
docker_storage_dir: /var/lib/docker
docker_state_dir: /run/docker

docker_http_proxy: "{{ http_proxy | default('') }}"
docker_https_proxy: "{{ https_proxy | default('') }}"
docker_no_proxy: "{{ no_proxy | default('') }}"
